In [14]:
#Valid Sudukooo............................................
import numpy as np
a=np.array(eval(input("Enter the Array")))
temp=0
k=0
p=0
for i in range(0,9):
    b=a[i]
    if b.sum()!=45:
        print("Not the valid Sudukoo....")
        temp=1
        break
    c=a[:,i]
    if c.sum()!=45:
        print("Not the valid Sudukoo....")
        temp=1
        break
    if i!=0 and i%3==0:
        k=k+3
        p=0
    if i!=0 and i%3!=0:
        p=p+3
    d=a[k:k+3,p:p+3]
    if d.sum()!=45:
        print("Not the valid sudukoo....")
        temp=1
        break
if temp!=1:
    print("It is the valid Sudukoo....")

Enter the Array[     [5, 3, 5, 6, 7, 8, 9, 1, 2],     [6, 7, 2, 1, 9, 5, 3, 4, 8],     [1, 9, 8, 3, 4, 2, 5, 6, 7],     [8, 5, 9, 7, 6, 1, 4, 2, 3],     [4, 2, 6, 8, 5, 3, 7, 9, 1],     [7, 1, 3, 9, 2, 4, 8, 5, 6],     [9, 6, 1, 5, 3, 7, 2, 8, 4],     [2, 8, 7, 4, 1, 9, 6, 3, 5],     [3, 4, 5, 2, 8, 6, 1, 7, 9] ]
Not the valid Sudukoo....


In [48]:
import numpy as np
# Columns: [Age, Math Marks, Science Marks],
data = np.array([[18, 85, 78],   # Student 1
                 [19, 92, 88],   # Student 2
                 [17, 76, 95],   # Student 3
                 [18, 65, 70],   # Student 4
                 [20, 90, 85]    # Student 5
                ])

In [49]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [50]:
#Find the average age of students.
p=np.mean(data[:,0])
p

np.float64(18.4)

In [51]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [52]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [53]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [54]:
#Increase Math marks of all students by 5.
data[:,1]=data[:,1]+5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [55]:
#Find how many students are younger than 19.
data[data[:,0]<19,0].size

3

In [57]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [58]:
#Get data of students who scored at least 80 in both subjects.
data[np.sum(data[:,1:],axis=1)>=80]

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [59]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75,2]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])